# The URL the site will be built for
base_url = "https://ar.reify.ing"

title = "AR at Reify.ing"
description = "AR/MR/XR Blogs at Reifying"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
minify_html = true

author = "FL<fl@reify.ing>"

theme = "float"

taxonomies = [
    {name = "tags", paginate_by = 10},
]

[languages.en]
# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
smart_punctuation = true
lazy_async_image = true

[extra]
# Put all your custom variables here
copyright = "[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)"
